#!/bin/bash
# Fail on error
set -e

# Remove old environment
mamba env remove -n nesoi

# Create and activate a new conda environment
# This manages most of the dependencies
LDFLAGS="-L$(brew --prefix libheif)/lib" CFLAGS="-I$(brew --prefix libheif)/include" mamba env create -f environment.yml
source ~/miniconda3/bin/activate nesoi

mkdir -p repos
cd repos

# ===== Setup napari =====
git clone https://github.com/vispy/vispy.git
pip install --no-deps -e ./vispy

# ===== Setup napari =====
git clone git@github.com:kephale/napari.git
# git clone https://github.com/andy-sweet/napari
# git clone https://github.com/napari/napari
cd napari
git remote add upstream git@github.com:napari/napari.git
git remote add andy-sweet git@github.com:andy-sweet/napari.git
git remote add kephale git@github.com:kephale/napari.git

git fetch andy-sweet
git checkout andy-sweet/async-integrate-alternate

# git checkout -b async-slice-proto --track andy-sweet/async-slice-proto
cd ..
pip install -e ./napari

# ===== Setup napari-omero =====
git clone https://github.com/tlambert03/napari-omero.git
pip install --no-deps -e ./napari-omero

# ===== Setup napari-console =====
git clone https://github.com/napari/napari-console.git
pip install --no-deps -e ./napari-console

# ===== Setup napari-animation =====
git clone https://github.com/napari/napari-animation.git
pip install --no-deps -e ./napari-animation

# ===== Setup napari-imaris =====
git clone https://github.com/CBI-PITT/napari-imaris-loader
pip install --no-deps -e ./napari-imaris-loader

# ===== Setup napari-turing =====
git clone https://github.com/leoguignard/napari-turing
pip install --no-deps -e ./napari-turing

# ===== Setup napari-stable-diffusion =====
git clone git@github.com:kephale/napari-stable-diffusion.git
pip install --no-deps -e ./napari-stable-diffusion

# ===== Setup tyssue =====
jupyter nbextension install --sys-prefix --py pythreejs
jupyter nbextension enable --sys-prefix --py pythreejs
jupyter nbextension enable --py widgetsnbextension

git clone --recursive https://github.com/DamCB/tyssue
pip install --no-deps -e ./tyssue

git clone https://github.com/DamCB/tyssue-demo
git clone https://github.com/DamCB/tyssue-notebooks

# ===== Setup napari-tyssue =====
git clone git@github.com:kephale/napari-tyssue.git
pip install --no-deps -e ./napari-tyssue

# ===== Setup napari-stack-processing =====
git clone git@github.com:kephale/napari-stack-processing.git
pip install --no-deps -e ./napari-stack-processing

# ===== Setup napari-bigdataviewer =====
git clone git@github.com:kephale/napari-bigdataviewer.git
pip install --no-deps -e ./napari-bigdataviewer

# ===== Setup napari-multiscale-rendering-prototype =====
git clone git@github.com:kephale/napari-multiscale-rendering-prototype.git
pip install --no-deps -e ./napari-multiscale-rendering-prototype

# corgie from seung lab
git clone git@github.com:seung-lab/corgie.git
pip install --no-deps -e ./corgie

# ===== Setup napari-hierarchical =====
git clone git@github.com:kephale/napari-hierarchical.git
pip install --no-deps -e ./napari-hierarchical

# ===== Setup napari-ome-zarr =====
git clone https://github.com/ome/napari-ome-zarr.git
pip install --no-deps -e ./napari-ome-zarr

# ===== Setup napari-image-generators =====
git clone git@github.com:kephale/napari-image-generators.git
pip install --no-deps -e ./napari-image-generators

# More plugins (i know this could be in the yml):
pip install --no-deps git+https://github.com/morphometrics/morphometrics-engine.git
pip install --no-deps napari-stress
pip install --no-deps napari-pymeshlab
pip install --no-deps git+https://github.com/kevinyamauchi/morphometrics.git
pip install --no-deps napari-skimage-regionprops
pip install --no-deps napari-geojson
pip install --no-deps napari-plot-profile
# deconvolution
pip install --no-deps redlionfish
pip install --no-deps btrack
pip install --no-deps git+https://github.com/lowe-lab-ucl/arboretum.git
pip install --no-deps git+https://github.com/hanjinliu/napari-spreadsheet.git



# pip install --no-deps git+https://github.com/BodenmillerGroup/napari-hierarchical.git

# Compatibility issues
#pip install napari-nD-annotator# "numpy.core.multiarray failed to import"

# ===== midi =====

# git clone https://github.com/jupyter-widgets/midicontrols
# pip install --no-deps -e ./midicontrols
