name: nesoi
channels:
- pytorch-nightly
- conda-forge
dependencies:  
# 3.9 because of pytorch, triangle, simplejpeg
- python=3.10
- "setuptools=59.5.0"
# issue with cmake from conda on macos 13?
#- cmake
- pybind11
- pip
- boost-cpp
- mpfr
- gmp
- cgal
- numpy
- scyjava >= 1.8.1
- scipy
- matplotlib
- pandas
- pytables
- jupyter
- notebook
- quantities
- ipywidgets
- pythreejs
- ipyvolume
#- vispy
- meshio
- zarr
- xarray
- hdf5
- mpfr
- gmp
- pyvista
- pyqt
- omero-py
- pyimagej >= 1.4.0
- pyopencl
- reikna
- openjdk=11
- jupyterlab
- pytorch
- torchvision
- diffusers
- einops
- fire
- maven
- pillow
- openjpeg
- imagecodecs
- "bokeh>=2.4.2,<3"
- python-graphviz
- ipycytoscape
- fftw
- napari-segment-blobs-and-things-with-membranes
- s3fs
- pooch
- qtpy
- superqt
- yappi
- ftfy
- tqdm
- imageio
- pyarrow
- squidpy
- h5py
- tifffile
- nilearn
- flake8
- pytest
- asv
- pint
- pytest-qt
- pytest-cov
- mypy
- opencv
- flask
- vedo
- vtk
- libnetcdf
- ruff
- qscintilla2
- confuse
- jpype1 >= 1.4.1
- labeling >= 0.1.12
- lazy_loader
- lxml
- ocl_icd_wrapper_apple
- ninja
- pythran
- gql
- boto3
- pip:
# compilation error with python 3.10/clang on m1    
#    - triangle
    - idr-py
    - album
    - omero-rois
    - imageio-ffmpeg
    - transformers
    - gradio
    - imaris-ims-file-reader
    - scanpy
    - pyarrow
#    - imagecodecs
    - invagination
    - hypothesis
    - tensorstore
# introduces a simplejpeg dep that causes problems
#    - kimimaro
    - alabaster
    - compressed-segmentation
    - pyspng-seunglab
    - tabulous
    - imglyb
    - imglyb-bdv
    - fibsem_tools
    - pyheif
    - "ome-zarr>=0.3.0"
    - importmagic
    - epc
    - ruff
    - python-lsp-server[all]
    - pylsp-mypy
    - pyls-isort
    - python-lsp-black
    - pyls-memestra
    - pylsp-rope
    - python-lsp-ruff
    - snakeviz
    - pyaudio
    - Mastodon.py
    - qrcode
    - napari-process-points-and-surfaces
    - opencv-python-headless
#    - vedo
#    - aicsimageio
#    - napari-matplotlib
#    - "napari-process-points-and-surfaces>=0.3.0"
#    - "napari-tools-menu>=0.1.15"
    - pygeodesic
    - skan
    - napari-boids
    - napari-matplotlib
    - stardist-napari
    - cellpose-napari
    - stardist
    - "tensorflow-macos;  platform_system==\"Darwin\" and platform_machine==\"arm64\""
    - "tensorflow-metal;  platform_system==\"Darwin\" and platform_machine==\"arm64\""
    - pydantic-ome-ngff
    - python-dotenv
    - validate-pyproject[all]
    - segment-anything
    - ndjson
    - requests_toolbelt
#    - 'cmake>=3.25.2'
#    - "pyshtools<=4.10.0"
#    - ipymidicontrols
# requires 3.10
#    - bpy
