name: nesoi
channels:
- pytorch-nightly
- conda-forge
dependencies:
- python=3.9  
- cmake
- pybind11
- pip
- boost-cpp
- mpfr
- gmp
- cgal
- python>=3.6
- numpy
- scyjava
- scipy
- matplotlib
- pandas
- pytables
- jupyter
- notebook
- quantities
- ipywidgets
- pythreejs
- ipyvolume
#- vispy
- meshio
- zarr
- xarray
- ipywidgets
- hdf5
- mpfr
- gmp
- pyvista
- pyqt
- omero-py
- pyimagej
- pyopencl
- reikna
- openjdk=11
- jupyterlab
- pytorch
- torchvision
- diffusers
- einops
- fire
- maven
- pillow
- openjpeg
- imagecodecs
- "bokeh>=2.4.2,<3"
- pip:
    - s3fs
    - pooch
    - qtpy
    - superqt
    - yappi
    - triangle
    - idr-py
    - album
    - omero-rois
    - imageio-ffmpeg
    - transformers
    - ftfy
    - gradio
    - imaris-ims-file-reader
    - tqdm
    - scanpy
    - pyarrow
#    - imagecodecs
    - squidpy
    - imageio
    - h5py
    - tifffile
    - nilearn
    - flake8
    - invagination
    - pytest
    - pytest-qt
    - pytest-cov
    - hypothesis
    - tensorstore
    - kimimaro
    - alabaster
    - compressed-segmentation
    - pyspng-seunglab
    - tabulous
    - imglyb
    - imglyb-bdv
    - mypy
    - asv
    - fibsem_tools
    - pyheif
    - "ome-zarr>=0.3.0"
#    - ipymidicontrols
